window.gcexports.globalLexicon = {
    "let" : { "tk": 18, "cls": "keyword" },
    "if" : { "tk": 5, "cls": "keyword" },
    "then" : { "tk": 6, "cls": "keyword" },
    "else" : { "tk": 7, "cls": "keyword" },
    "case" : { "tk": 15, "cls": "keyword" },
    "of" : { "tk": 16, "cls": "keyword" },
    "end" : { "tk": 17, "cls": "keyword", "length": 0 },
    "true" : { "tk": 20, "cls": "val", "length": 0 },
    "false" : { "tk": 20, "cls": "val", "length": 0 },
    "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
    "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
    "addD" : { "tk": 1, "name": "ADDD", "cls": "function", "length": 2 , "arity": 2 },
    "mulD" : { "tk": 1, "name": "MULD", "cls": "function", "length": 2 , "arity": 2 },
    "data" : { "tk" : 1, "name": "DATA", "cls": "function", "length": 1, "arity": 1 },
    "bar" : { "tk": 1, "name": "BAR", "cls": "function", "length": 1, "arity": 1},
    "radial" : { "tk": 1, "name": "RADIAL", "cls": "function", "length": 1, "arity": 1},
    "animate" : { "tk": 1, "name": "ANIMATE", "cls": "function", "length": 2, "arity": 2},
    "size" : { "tk": 1, "name": "SIZE", "cls" : "function", "length": 2, "arity": 2},
    "rgb" : { "tk": 1, "name": "RGB", "cls" : "function", "length": 3, "arity": 3},
    "rgba" : { "tk": 1, "name": "RGBA", "cls" : "function", "length": 4, "arity": 4},
    "thickness" : { "tk": 1, "name": "THICK", "cls" : "function", "length": 2, "arity": 2},
    "rotate" : { "tk": 1, "name": "ROTATE", "cls": "function", "length": 2, "arity": 2},
    "fraction" : { "tk": 1, "name": "FRACTION", "cls": "function", "length": 1, "arity": 1},
    "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
    "bar-background" : { "tk": 1, "name": "BBGD", "cls": "function", "length": 2, "arity": 2},
    "fill" : { "tk": 1, "name": "FILL", "cls": "function", "length": 2, "arity": 2},
    "backopacity" : { "tk": 1, "name": "BACKOPACITY", "cls": "function", "length": 2, "arity": 2},
    "opacity" : { "tk": 1, "name": "OPACITY", "cls": "function", "length": 2, "arity": 2},
    "background" : { "tk": 1, "name": "BGD", "cls": "function", "length": 1, "arity": 1},
    "rounding" : { "tk": 1, "name": "ROUNDING", "cls": "function", "length": 2, "arity": 2},
    "inner-radius" : { "tk": 1, "name": "INNER", "cls": "function", "length": 2, "arity": 2},
    "outer-radius" : { "tk": 1, "name": "OUTER", "cls": "function", "length": 2, "arity": 2},
    "labels" : { "tk": 1, "name": "LABELS", "cls": "function", "length": 2, "arity": 2},
    "dividers" : { "tk": 1, "name": "DIVIDERS", "cls": "function", "length": 2, "arity": 2},
    "divider-width" : { "tk": 1, "name": "DIVWIDTH", "cls": "function", "length": 2, "arity": 2},
    "brewer" : { "tk": 1, "name": "BREWER", "cls": "function", "length": 2, "arity": 2},
    "gap" : { "tk": 1, "name": "GAP", "cls": "function", "length": 2, "arity": 2},
    "get" : { "tk" : 1, "name": "GET", "cls": "function", "length": 1, "arity": 1 },
    "secondary-bar" : { "tk": 1, "name": "SECBAR", "cls": "function", "length": 1, "arity": 1},
    "arc" : { "tk": 1, "name": "ARC", "cls": "function", "length": 2, "arity": 2},
    "text" : { "tk": 1, "name": "TEXT", "cls": "function", "length": 2, "arity": 2},
    "image" : { "tk": 1, "name": "IMAGE", "cls": "function", "length": 5, "arity": 5}
}
